# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9
    environment:
      MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix do deps.get, deps.compile
      - save_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
            - ~/.mix
            - _build
      - run: mix compile
      - run: echo "$OTP_VERSION $ELIXIR_VERSION" > .version_file
      - restore_cache:
          key: plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}
      - run: mix dialyzer --plt
      - save_cache:
          key: plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}
          paths:
            - deps
            - ~/.mix
            - _build

  check_format:
    docker:
      - image: circleci/elixir:1.9
    environment:
      MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix format --check-formatted

  credo:
    docker:
      - image: circleci/elixir:1.9
    environment:
      MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix credo

  dialyzer:
    docker:
      - image: circleci/elixir:1.9
    environment:
      MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "$OTP_VERSION $ELIXIR_VERSION" > .version_file
      - restore_cache:
          key: plt-cache-{{ checksum ".version_file" }}-{{ checksum "mix.lock" }}
      - run: mix dialyzer --halt-exit-status

  documentation:
    docker:
      - image: circleci/elixir:1.9
    environment:
      MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix docs
      - store_artifacts:
          path: doc
          destination: documentation

  test:
    docker:
      - image: circleci/elixir:1.9
    environment:
      MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps-cache-{{ checksum "mix.lock" }}
      - run: mix test

  # release:
  #   branches:
  #     only:
  #       - master
  #   docker:
  #     - image: circleci/elixir:1.9
  #   working_directory: ~/repo
  #   steps:
  #     -

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
          filters:
            branches:
              only:
                - master
                - develop
      - check_format:
          requires:
            - build
      - credo:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - dialyzer:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - documentation:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop

      # - release:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
